# Service descriptions for TsuryPhone integration
# Each service targets a TsuryPhone device via the service target selector.
dial:
  name: Dial number
  description: Dial a phone number on the TsuryPhone device.
  target:
    device:
      integration: tsuryphone
  fields:
    number:
      name: Phone number
      description: Number to dial (quote to preserve leading zeros).
      required: true
      example: "0541234567"
      selector:
        text:

answer:
  name: Answer call
  description: Answer an incoming call on the TsuryPhone device.
  target:
    device:
      integration: tsuryphone

hangup:
  name: Hang up call
  description: Hang up an active call on the TsuryPhone device.
  target:
    device:
      integration: tsuryphone

ring_device:
  name: Ring device
  description: Trigger the TsuryPhone device to ring.
  target:
    device:
      integration: tsuryphone
  fields:
    pattern:
      name: Ring pattern
      description: Optional ring pattern string.
      required: false
      example: "300,300,300"
      selector:
        text:
    force:
      name: Bypass DND
      description: Whether to enforce ringing even when Do Not Disturb is active.
      required: false
      default: false
      selector:
        boolean:

set_ring_pattern:
  name: Set ring pattern
  description: Update the ring pattern on the TsuryPhone device.
  target:
    device:
      integration: tsuryphone
  fields:
    pattern:
      name: Ring pattern
      description: Ring pattern string to apply.
      required: true
      example: "300,300,300"
      selector:
        text:

reset_device:
  name: Reset device
  description: Reboot the TsuryPhone device.
  target:
    device:
      integration: tsuryphone

factory_reset_device:
  name: Factory reset device
  description: Wipe stored configuration, statistics, and Wi-Fi credentials, then reboot.
  target:
    device:
      integration: tsuryphone

set_dnd:
  name: Set Do Not Disturb
  description: Configure Do Not Disturb settings on the TsuryPhone device.
  target:
    device:
      integration: tsuryphone
  fields:
    force:
      name: Force DND
      description: Force DND mode on or off.
      required: false
      example: true
      selector:
        boolean:
    scheduled:
      name: Scheduled DND
      description: Enable scheduled DND handling.
      required: false
      example: true
      selector:
        boolean:
    start_hour:
      name: Start hour
      description: Start hour (0-23).
      required: false
      example: 22
      selector:
        number:
          min: 0
          max: 23
    start_minute:
      name: Start minute
      description: Start minute (0-59).
      required: false
      example: 30
      selector:
        number:
          min: 0
          max: 59
    end_hour:
      name: End hour
      description: End hour (0-23).
      required: false
      example: 7
      selector:
        number:
          min: 0
          max: 23
    end_minute:
      name: End minute
      description: End minute (0-59).
      required: false
      example: 0
      selector:
        number:
          min: 0
          max: 59

set_audio:
  name: Set audio configuration
  description: Update audio gain/volume settings.
  target:
    device:
      integration: tsuryphone
  fields:
    earpiece_volume:
      name: Earpiece volume
      description: Value between 1 and 7.
      required: false
      example: 4
      selector:
        number:
          min: 1
          max: 7
    earpiece_gain:
      name: Earpiece gain
      description: Value between 1 and 7.
      required: false
      example: 5
      selector:
        number:
          min: 1
          max: 7
    speaker_volume:
      name: Speaker volume
      description: Value between 1 and 7.
      required: false
      example: 6
      selector:
        number:
          min: 1
          max: 7
    speaker_gain:
      name: Speaker gain
      description: Value between 1 and 7.
      required: false
      example: 5
      selector:
        number:
          min: 1
          max: 7

get_call_history:
  name: Get call history
  description: Retrieve call history entries from the integration cache.
  target:
    device:
      integration: tsuryphone
  fields:
    limit:
      name: Limit
      description: Maximum number of entries to return.
      required: false
      example: 50
      selector:
        number:
          min: 1
          max: 1000

clear_call_history:
  name: Clear call history
  description: Clear stored call history entries.
  target:
    device:
      integration: tsuryphone
  fields:
    older_than_days:
      name: Older than (days)
      description: Remove entries older than the specified number of days.
      required: false
      example: 30
      selector:
        number:
          min: 1
    keep_last:
      name: Keep last
      description: Keep the specified number of most recent entries.
      required: false
      example: 100
      selector:
        number:
          min: 1

quick_dial_add:
  name: Add quick dial entry
  description: Add a quick dial shortcut.
  target:
    device:
      integration: tsuryphone
  fields:
    code:
      name: Quick dial code
      description: Quick dial code (quote to preserve leading zeros).
      required: true
      example: "012"
      selector:
        text:
    number:
      name: Phone number
      description: Phone number to dial when using the quick dial entry.
      required: true
      example: "0541234567"
      selector:
        text:
    name:
      name: Display name
      description: Optional label for the quick dial entry.
      required: false
      example: "Mom"
      selector:
        text:

quick_dial_remove:
  name: Remove quick dial entry
  description: Remove a quick dial shortcut by code.
  target:
    device:
      integration: tsuryphone
  fields:
    code:
      name: Quick dial code
      description: Quick dial code to remove from the device.
      required: true
      example: "012"
      selector:
        text:

quick_dial_clear:
  name: Clear quick dial entries
  description: Remove all quick dial shortcuts from the device.
  target:
    device:
      integration: tsuryphone

blocked_add:
  name: Add blocked number
  description: Add a phone number to the blocked list.
  target:
    device:
      integration: tsuryphone
  fields:
    number:
      name: Phone number
      description: Phone number that should be blocked.
      required: true
      example: "0541234567"
      selector:
        text:
    reason:
      name: Reason
      description: Optional reason to display.
      required: false
      example: "Telemarketer"
      selector:
        text:

blocked_remove:
  name: Remove blocked number
  description: Remove a phone number from the blocked list.
  target:
    device:
      integration: tsuryphone
  fields:
    number:
      name: Phone number
      description: Phone number to remove from the blocked list.
      required: true
      example: "0541234567"
      selector:
        text:

blocked_clear:
  name: Clear blocked numbers
  description: Remove all blocked numbers from the device.
  target:
    device:
      integration: tsuryphone

priority_add:
  name: Add priority caller
  description: Mark a phone number as a priority caller.
  target:
    device:
      integration: tsuryphone
  fields:
    number:
      name: Phone number
      description: Phone number to mark as a priority caller.
      required: true
      example: "0541112222"
      selector:
        text:

priority_remove:
  name: Remove priority caller
  description: Remove a phone number from the priority list.
  target:
    device:
      integration: tsuryphone
  fields:
    number:
      name: Phone number
      description: Phone number to remove from the priority list.
      required: true
      example: "0541112222"
      selector:
        text:

refetch_all:
  name: Refetch device data
  description: Ask the device to refresh and resend configuration data.
  target:
    device:
      integration: tsuryphone

get_diagnostics:
  name: Get diagnostics
  description: Retrieve diagnostics information from the device.
  target:
    device:
      integration: tsuryphone

get_tsuryphone_config:
  name: Get TsuryPhone configuration
  description: Retrieve the full configuration snapshot from the device.
  target:
    device:
      integration: tsuryphone

webhook_add:
  name: Add webhook action
  description: Register a webhook action on the device.
  target:
    device:
      integration: tsuryphone
  fields:
    url:
      name: Webhook URL
      description: Full URL to call when the action triggers.
      required: true
      example: "https://example.com/api/webhook/tsuryphone"
      selector:
        text:
    events:
      name: Events
      description: Event names that should trigger this webhook.
      required: true
      example: '["call_start", "ring"]'
      selector:
        object:
    name:
      name: Display name
      description: Optional label for the webhook action.
      required: false
      example: "Notify on call start"
      selector:
        text:

webhook_remove:
  name: Remove webhook action
  description: Remove a webhook action from the device.
  target:
    device:
      integration: tsuryphone
  fields:
    url:
      name: Webhook URL
      description: Webhook URL to remove from the device.
      required: true
      example: "https://example.com/api/webhook/tsuryphone"
      selector:
        text:

webhook_clear:
  name: Clear webhook actions
  description: Remove all webhook actions from the device.
  target:
    device:
      integration: tsuryphone

webhook_test:
  name: Test webhook
  description: Trigger a webhook action as a test.
  target:
    device:
      integration: tsuryphone
  fields:
    url:
      name: Webhook URL
      description: Webhook URL to invoke for the test.
      required: true
      example: "https://example.com/api/webhook/tsuryphone"
      selector:
        text:

switch_call_waiting:
  name: Switch call waiting
  description: Toggle the active call when call waiting is available.
  target:
    device:
      integration: tsuryphone

set_maintenance_mode:
  name: Set maintenance mode
  description: Enable or disable maintenance mode on the device.
  target:
    device:
      integration: tsuryphone
  fields:
    enabled:
      name: Enabled
      description: Whether maintenance mode should be enabled.
      required: true
      example: true
      selector:
        boolean:

get_missed_calls:
  name: Get missed calls
  description: Retrieve missed call entries from the integration cache.
  target:
    device:
      integration: tsuryphone

dial_quick_dial:
  name: Dial quick dial code
  description: Dial using a quick dial code stored on the device.
  target:
    device:
      integration: tsuryphone
  fields:
    code:
      name: Quick dial code
      description: Stored quick dial code to dial.
      required: true
      example: "012"
      selector:
        text:

set_ha_url:
  name: Set Home Assistant URL
  description: Configure the Home Assistant base URL used by the device for webhooks.
  target:
    device:
      integration: tsuryphone
  fields:
    url:
      name: URL
      description: Base URL that the device should call back to.
      required: true
      example: "https://homeassistant.local:8123"
      selector:
        text:

quick_dial_import:
  name: Import quick dial entries
  description: Import multiple quick dial entries at once.
  target:
    device:
      integration: tsuryphone
  fields:
    entries:
      name: Entries
      description: List of quick dial entries to import.
      required: true
      example: '[{"code": "01", "number": "0541234567", "name": "Mom"}]'
      selector:
        object:
    clear_existing:
      name: Clear existing entries
      description: Remove existing quick dial entries before importing.
      required: false
      example: true
      selector:
        boolean:

quick_dial_export:
  name: Export quick dial entries
  description: Retrieve quick dial entries from the integration cache.
  target:
    device:
      integration: tsuryphone

blocked_import:
  name: Import blocked numbers
  description: Import multiple blocked numbers.
  target:
    device:
      integration: tsuryphone
  fields:
    entries:
      name: Entries
      description: List of blocked number entries to import.
      required: true
      example: '[{"number": "0547654321", "reason": "Spam caller"}]'
      selector:
        object:
    clear_existing:
      name: Clear existing entries
      description: Remove existing blocked numbers before importing.
      required: false
      example: true
      selector:
        boolean:

blocked_export:
  name: Export blocked numbers
  description: Retrieve blocked numbers from the integration cache.
  target:
    device:
      integration: tsuryphone

resilience_status:
  name: Get resilience status
  description: Retrieve diagnostic information from the resilience manager.
  target:
    device:
      integration: tsuryphone

resilience_test:
  name: Run resilience test
  description: Execute a resilience diagnostic test (connection, sequence, or stress).
  target:
    device:
      integration: tsuryphone
  fields:
    test_type:
      name: Test type
      description: Type of resilience test to run.
      required: false
      example: sequence
      selector:
        select:
          options:
            - connection
            - sequence
            - stress

websocket_reconnect:
  name: Force websocket reconnect
  description: Force the integration to reconnect the websocket client.
  target:
    device:
      integration: tsuryphone

run_health_check:
  name: Run health check
  description: Perform a comprehensive health check through the resilience manager.
  target:
    device:
      integration: tsuryphone
