name: Auto Release On Push

on:
  push:
    branches: [ main ]

concurrency:
  group: auto-release-main
  cancel-in-progress: false

jobs:
  auto-release:
    if: "!contains(github.event.head_commit.message, 'chore(auto-release)') && !contains(github.event.head_commit.message, '[skip-release]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to push tag & release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read current version
        id: ver
        run: |
          CURR=$(jq -r '.version' custom_components/tsuryphone/manifest.json)
          if [ -z "$CURR" ] || [ "$CURR" = "null" ]; then
            echo "Failed to read version from manifest.json" >&2
            exit 1
          fi
          echo "current=$CURR" >> $GITHUB_OUTPUT
          echo "Current version: $CURR"

      - name: Bump patch version
        id: bump
        run: |
          CURR='${{ steps.ver.outputs.current }}'
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURR"
          if [ -z "$MAJOR" ] || [ -z "$MINOR" ] || [ -z "$PATCH" ]; then
            echo "Invalid current version: $CURR" >&2
            exit 1
          fi
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "new=$NEW_VERSION" >> $GITHUB_OUTPUT
          tmpfile=$(mktemp)
          jq --arg v "$NEW_VERSION" '.version=$v' custom_components/tsuryphone/manifest.json > "$tmpfile" && mv "$tmpfile" custom_components/tsuryphone/manifest.json
          echo "Bumped to: $NEW_VERSION"

      - name: Commit version bump
        run: |
          NEW='${{ steps.bump.outputs.new }}'
          git config user.email "action@github.com"
            
          git config user.name "auto-release"
          git add custom_components/tsuryphone/manifest.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore(auto-release): bump version to $NEW"
          git push origin HEAD:main

      - name: Create zip package
        run: |
          NEW='${{ steps.bump.outputs.new }}'
          cd custom_components
          zip -r ../tsuryphone-$NEW.zip tsuryphone/
          cd ..
          sha256sum tsuryphone-$NEW.zip > tsuryphone-$NEW.zip.sha256
          echo "Package created:"; ls -l tsuryphone-$NEW.zip*

      - name: Create tag
        run: |
          NEW='${{ steps.bump.outputs.new }}'
          git tag -a v$NEW -m "Auto release v$NEW"
          git push origin v$NEW

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump.outputs.new }}
          name: v${{ steps.bump.outputs.new }}
          body: |
            Automated release for commit ${{ github.sha }}.
            Version: v${{ steps.bump.outputs.new }}
          files: |
            tsuryphone-${{ steps.bump.outputs.new }}.zip
            tsuryphone-${{ steps.bump.outputs.new }}.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "Released v${{ steps.bump.outputs.new }}" >> $GITHUB_STEP_SUMMARY
